SLL: SLL.c
	gcc SLL.c -o ../output/SLL -Wall -Wextra

DLL: DLL.c
	gcc DLL.c -o ../output/DLL -Wall -Wextra

circularSLL: circularSLL.c
	gcc circularSLL.c -o ../output/circularSLL -Wall -Wextra

circularDLL: circularDLL.c
	gcc circularDLL.c -o ../output/circularDLL -Wall -Wextra
